version: "3.8"
services:
  web:
    build: .
    ports: 
      - "4000:80"
    volumes:
      - .:/app
    depends_on:
      - redis
  postgres:
    - var/hkf/kskdskd

  redis:
    image: "redis:alpine"
